version: '2'
services:

    web:
        build: ./web
        restart: unless-stopped
        env_file: ./web/app.env
        volumes:
        - ./web:/usr/src/app
        - /static:/static
        depends_on:
          - redis
          - postgres
        expose:
          - "8003"
        command: gunicorn ecommerce.wsgi -b 0.0.0.0:8003

    postgres:
        build: ./postgres
        restart: unless-stopped
        env_file: ./web/app.env
        expose:
            - "5432"
        environment:   # will be used by the init script
            LC_ALL: C.UTF-8
        volumes:
            - ./postgres/data:/var/lib/postgresql/data/  # persist container's db data to local pgdata/ (mounted)

    redis:
        image: sickp/alpine-redis:3.2.2
        restart: unless-stopped
        expose:
            - "6379"
        volumes:
            - redisdata:/data

    nginx:
        restart: unless-stopped
        build: ./nginx/
        ports:
          - "8003:80"
        volumes:
          - /static:/static
        links:
          - web

volumes:
  redisdata:



